### Welcome to Paradox-Scout Jekyll! ###
########################################
# There is a bit of configuring before you can get up and running with Paradox-Scout

### Base Site settings ###
##########################

title: GlobalDynamics Scout # site title, also used in the navbar
email: 4026scouting@gmail.com
description: "A First Robotics Scouting Application built by Team Paradox 2102 and used by Team 4026" # site description
baseurl: "/roborecon-app" # the subpath of your site, e.g. /blog
url: "https://decatur-high-globaldynamics.github.io/roborecon-app/" # the base hostname & protocol for your site


### Header Settings ###
#######################
# Customise to how you want
header:
    title: Team GlobalDynamics 4026 # the bold, bigger main text
    accent: 2019 Scouting System # the smaller, but informative accenting text
    logo: "/images/4026logo.png" # FULL path to image in the header 150x150 works well

### Footer Settings ###
#######################
# Customise to how you want
footer:
    facebook: "https://www.facebook.com/GlobalDyamics/"
    twitter: "https://twitter.com/frc4026"
    github: "https://github.com/Decatur-High-GlobalDynamics/" 


### Scouting System Settings ###
################################
# These are the most imporant settings, choose carefully

scout:
    teamkey: 4026
    tbaApiKey: RDRZz312LSbpkbR2vgGMsrICdg7BDO3CLNpV4VyvwS6oJFDckAamNCGF2vM9ngVP
    currentevent: 2019week0 # the Event key for the event you want to scout, can be found on TBA
    firebase:
        rooturl: https://paradox-scout-dc256.firebaseio.com/ # Address of Firebase Server
        apikey: AIzaSyDleJPx9RQChKn4DlLV9nXqMNafP7BvhG0 # API Key of Firebase
        authdomain: paradox-scout-dc256.firebaseapp.com # Domain for Firebase to Connect to
        databaseurl: https://paradox-scout-dc256.firebaseio.com # Domain for Firebase Database to Connect to
        storagebucket: paradox-scout-dc256.appspot.com # Domain for Firebase Storage Bucket to Connect to
        messagingsenderid: 777517430963 # ID for message sender

### Other Jekyll###
###################
# You should never have to change these.
encoding: utf-8
exclude: [vendor]
